volumes:
  - "/usr/lib/aarch64-linux-gnu/libgstnvegl-1.0.so.0:/usr/lib/aarch64-linux-gnu/libgstnvegl-1.0.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideosinks.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideosinks.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglstreamsrc.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglstreamsrc.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvegltransform.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvegltransform.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideo4linux2.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideo4linux2.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvarguscamerasrc.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvarguscamerasrc.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvivafilter.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvivafilter.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideocuda.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideocuda.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvdrmvideosink.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvdrmvideosink.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideosink.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideosink.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvjpeg.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvjpeg.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvidconv.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvidconv.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvtee.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvtee.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglglessink.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglglessink.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstnvexifmeta.so:/usr/lib/aarch64-linux-gnu/libgstnvexifmeta.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstnvivameta.so:/usr/lib/aarch64-linux-gnu/libgstnvivameta.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstnvegl-1.0.so.0:/usr/lib/aarch64-linux-gnu/libgstnvegl-1.0.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideosinks.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideosinks.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglstreamsrc.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglstreamsrc.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvegltransform.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvegltransform.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideo4linux2.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideo4linux2.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvarguscamerasrc.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvarguscamerasrc.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvivafilter.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvivafilter.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideocuda.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideocuda.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvdrmvideosink.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvdrmvideosink.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideosink.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvideosink.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvjpeg.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvjpeg.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvidconv.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvvidconv.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvtee.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvtee.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglglessink.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglglessink.so:ro"
  - "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstnvexifmeta.so:/usr/lib/aarch64-linux-gnu/libgstnvexifmeta.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstnvivameta.so:/usr/lib/aarch64-linux-gnu/libgstnvivameta.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstbadaudio-1.0.so.0.1405.0:/usr/lib/aarch64-linux-gnu/libgstbadaudio-1.0.so.0.1405.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstbadaudio-1.0.so.0:/usr/lib/aarch64-linux-gnu/libgstbadaudio-1.0.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstbadvideo-1.0.so.0:/usr/lib/aarch64-linux-gnu/libgstbadvideo-1.0.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libgstbadvideo-1.0.so.0.1405.0:/usr/lib/aarch64-linux-gnu/libgstbadvideo-1.0.so.0.1405.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0:/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLEWmx.so.1.13.0:/usr/lib/aarch64-linux-gnu/libGLEWmx.so.1.13.0:ro"
  - "/usr/lib/aarch64-linux-gnu/tegra-egl/libGLESv2_nvidia.so.2:/usr/lib/aarch64-linux-gnu/tegra-egl/libGLESv2_nvidia.so.2:ro"
  - "/usr/lib/aarch64-linux-gnu/tegra-egl/libGLESv1_CM_nvidia.so.1:/usr/lib/aarch64-linux-gnu/tegra-egl/libGLESv1_CM_nvidia.so.1:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLX.so.0.0.0:/usr/lib/aarch64-linux-gnu/libGLX.so.0.0.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLESv2.so.2:/usr/lib/aarch64-linux-gnu/libGLESv2.so.2:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLEWmx.so.1.13:/usr/lib/aarch64-linux-gnu/libGLEWmx.so.1.13:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLU.so.1:/usr/lib/aarch64-linux-gnu/libGLU.so.1:ro"
  - "/usr/lib/aarch64-linux-gnu/libGL.so.1.0.0:/usr/lib/aarch64-linux-gnu/libGL.so.1.0.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLU.so.1.3.1:/usr/lib/aarch64-linux-gnu/libGLU.so.1.3.1:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0.0.0:/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0.0.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0.0.0:/usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0.0.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLU.so:/usr/lib/aarch64-linux-gnu/libGLU.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLESv2.so:/usr/lib/aarch64-linux-gnu/libGLESv2.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libGL.so.1:/usr/lib/aarch64-linux-gnu/libGL.so.1:ro"
  - "/usr/lib/aarch64-linux-gnu/tegra/libGLX_nvidia.so.0:/usr/lib/aarch64-linux-gnu/tegra/libGLX_nvidia.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLESv1_CM.so.1.0.0:/usr/lib/aarch64-linux-gnu/libGLESv1_CM.so.1.0.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLESv1_CM.so.1:/usr/lib/aarch64-linux-gnu/libGLESv1_CM.so.1:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLU.a:/usr/lib/aarch64-linux-gnu/libGLU.a:ro"
  - "/usr/lib/aarch64-linux-gnu/libGL.so:/usr/lib/aarch64-linux-gnu/libGL.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLX.so.0:/usr/lib/aarch64-linux-gnu/libGLX.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLESv2.so.2.0.0:/usr/lib/aarch64-linux-gnu/libGLESv2.so.2.0.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0:/usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLdispatch.so:/usr/lib/aarch64-linux-gnu/libGLdispatch.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLESv1_CM.so:/usr/lib/aarch64-linux-gnu/libGLESv1_CM.so:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLX_indirect.so.0:/usr/lib/aarch64-linux-gnu/libGLX_indirect.so.0:ro"
  - "/usr/lib/aarch64-linux-gnu/libGLX.so:/usr/lib/aarch64-linux-gnu/libGLX.so:ro"
  - "/etc/ld.so.conf.d/cuda-10-0.conf:/etc/ld.so.conf.d/cuda-10-0.conf:ro"
  - "/etc/nvidia-container-runtime/host-files-for-container.d/cuda.csv:/etc/nvidia-container-runtime/host-files-for-container.d/cuda.csv:ro"
  - "/etc/apt/sources.list.d/cuda-10-0-local-10.0.326.list:/etc/apt/sources.list.d/cuda-10-0-local-10.0.326.list:ro"
  - "/etc/alternatives/libcudnn:/etc/alternatives/libcudnn:ro"
  - "/etc/alternatives/libcudnn_so:/etc/alternatives/libcudnn_so:ro"
  - "/etc/alternatives/libcudnn_stlib:/etc/alternatives/libcudnn_stlib:ro"
  - "/etc/nvidia-container-runtime/host-files-for-container.d/cudnn.csv:/etc/nvidia-container-runtime/host-files-for-container.d/cudnn.csv:ro"
  - "/etc/ld.so.conf.d/nvidia-tegra.conf:/etc/ld.so.conf.d/nvidia-tegra.conf:ro"
  - "/etc/nvpmodel:/etc/nvpmodel:ro"
  - "/etc/nvpmodel/nvpmodel_t210_jetson-nano.conf:/etc/nvpmodel/nvpmodel_t210_jetson-nano.conf:ro"
  - "/etc/nvpmodel/nvpmodel_t210.conf:/etc/nvpmodel/nvpmodel_t210.conf:ro"
  - "/etc/skel/Desktop/nv_jetson_zoo.desktop:/etc/skel/Desktop/nv_jetson_zoo.desktop:ro"
  - "/etc/skel/Desktop/nv_devzone.desktop:/etc/skel/Desktop/nv_devzone.desktop:ro"
  - "/etc/skel/Desktop/nv_forums.desktop:/etc/skel/Desktop/nv_forums.desktop:ro"
  - "/etc/nv:/etc/nv:ro"
  - "/etc/nvpmodel.conf:/etc/nvpmodel.conf:ro"
  - "/etc/nvphsd_common.conf:/etc/nvphsd_common.conf:ro"
  - "/etc/nv_boot_control.conf:/etc/nv_boot_control.conf:ro"
  - "/etc/nvidia:/etc/nvidia:ro"
  - "/etc/nvidia-container-runtime:/etc/nvidia-container-runtime:ro"
  - "/etc/apt/sources.list.d/nvidia-l4t-apt-source.list:/etc/apt/sources.list.d/nvidia-l4t-apt-source.list:ro"
  - "/etc/nvphsd.conf:/etc/nvphsd.conf:ro"
  - "/etc/xdg/autostart/nvbackground.desktop:/etc/xdg/autostart/nvbackground.desktop:ro"
  - "/etc/xdg/autostart/nvpmodel_indicator.desktop:/etc/xdg/autostart/nvpmodel_indicator.desktop:ro"
  - "/etc/xdg/autostart/nvchrome.sh:/etc/xdg/autostart/nvchrome.sh:ro"
  - "/etc/xdg/autostart/nvbackground.sh:/etc/xdg/autostart/nvbackground.sh:ro"
  - "/etc/xdg/autostart/nvchrome.desktop:/etc/xdg/autostart/nvchrome.desktop:ro"
  - "/etc/apparmor.d/abstractions/nvidia:/etc/apparmor.d/abstractions/nvidia:ro"
  - "/etc/vulkan/icd.d/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json:ro"
  - "/etc/nv_tegra_release:/etc/nv_tegra_release:ro"
  - "/etc/systemd/timesyncd.conf.d/nv-fallback-ntp.conf:/etc/systemd/timesyncd.conf.d/nv-fallback-ntp.conf:ro"
  - "/etc/systemd/nvweston.sh:/etc/systemd/nvweston.sh:ro"
  - "/etc/systemd/nvgetty.sh:/etc/systemd/nvgetty.sh:ro"
  - "/etc/systemd/resolved.conf.d/nv-fallback-dns.conf:/etc/systemd/resolved.conf.d/nv-fallback-dns.conf:ro"
  - "/etc/systemd/nvmemwarning.sh:/etc/systemd/nvmemwarning.sh:ro"
  - "/etc/systemd/nvfb-early.sh:/etc/systemd/nvfb-early.sh:ro"
  - "/etc/systemd/nvzramconfig.sh:/etc/systemd/nvzramconfig.sh:ro"
  - "/etc/systemd/system/nv-l4t-usb-device-mode.service:/etc/systemd/system/nv-l4t-usb-device-mode.service:ro"
  - "/etc/systemd/system/nv-oem-config.target.wants:/etc/systemd/system/nv-oem-config.target.wants:ro"
  - "/etc/systemd/system/nv-oem-config.target.wants/nvfb-early.service:/etc/systemd/system/nv-oem-config.target.wants/nvfb-early.service:ro"
  - "/etc/systemd/system/nv-oem-config.target.wants/nvweston.service:/etc/systemd/system/nv-oem-config.target.wants/nvweston.service:ro"
  - "/etc/systemd/system/nvpmodel.service:/etc/systemd/system/nvpmodel.service:ro"
  - "/etc/systemd/system/nvs-service.service:/etc/systemd/system/nvs-service.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode.service:/etc/systemd/system/multi-user.target.wants/nv-l4t-usb-device-mode.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nv-l4t-bootloader-config.service:/etc/systemd/system/multi-user.target.wants/nv-l4t-bootloader-config.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvpmodel.service:/etc/systemd/system/multi-user.target.wants/nvpmodel.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvs-service.service:/etc/systemd/system/multi-user.target.wants/nvs-service.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvzramconfig.service:/etc/systemd/system/multi-user.target.wants/nvzramconfig.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvphs.service:/etc/systemd/system/multi-user.target.wants/nvphs.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvfb-early.service:/etc/systemd/system/multi-user.target.wants/nvfb-early.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvweston.service:/etc/systemd/system/multi-user.target.wants/nvweston.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nv.service:/etc/systemd/system/multi-user.target.wants/nv.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvgetty.service:/etc/systemd/system/multi-user.target.wants/nvgetty.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvargus-daemon.service:/etc/systemd/system/multi-user.target.wants/nvargus-daemon.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvfb.service:/etc/systemd/system/multi-user.target.wants/nvfb.service:ro"
  - "/etc/systemd/system/multi-user.target.wants/nvmemwarning.service:/etc/systemd/system/multi-user.target.wants/nvmemwarning.service:ro"
  - "/etc/systemd/system/nvzramconfig.service:/etc/systemd/system/nvzramconfig.service:ro"
  - "/etc/systemd/system/nvphs.service:/etc/systemd/system/nvphs.service:ro"
  - "/etc/systemd/system/nvfb-early.service:/etc/systemd/system/nvfb-early.service:ro"
  - "/etc/systemd/system/nvweston.service:/etc/systemd/system/nvweston.service:ro"
  - "/etc/systemd/system/nvwifibt.service:/etc/systemd/system/nvwifibt.service:ro"
  - "/etc/systemd/system/nv.service:/etc/systemd/system/nv.service:ro"
  - "/etc/systemd/system/nvgetty.service:/etc/systemd/system/nvgetty.service:ro"
  - "/etc/systemd/system/nvargus-daemon.service:/etc/systemd/system/nvargus-daemon.service:ro"
  - "/etc/systemd/system/nvfb.service:/etc/systemd/system/nvfb.service:ro"
  - "/etc/systemd/system/nvmemwarning.service:/etc/systemd/system/nvmemwarning.service:ro"
  - "/etc/systemd/system/nv-l4t-usb-device-mode-runtime.service:/etc/systemd/system/nv-l4t-usb-device-mode-runtime.service:ro"
  - "/etc/systemd/nv.sh:/etc/systemd/nv.sh:ro"
  - "/etc/systemd/nvwifibt.sh:/etc/systemd/nvwifibt.sh:ro"
  - "/etc/systemd/nvwifibt-pre.sh:/etc/systemd/nvwifibt-pre.sh:ro"
  - "/etc/systemd/nvfb.sh:/etc/systemd/nvfb.sh:ro"
